Install an Appsody Operator in preparation for deployment
appsody/appsody-docker pull request #18
Opened 2019-10-01 21:40 UTC by chilanti

The Tekton Pipeline example may fail if the new `app-deploy.yaml` manifests are checked into github (those require an Appsody operator, which may not be available in the `default` namespace).
This change adds the logic to install an appsody operator in the default namespace, and tolerates the presence of an appsody operator.
Fixes https://github.com/appsody/tekton-example/issues/22

2019-10-22 11:40 UTC, neeraj-laad requested changes
looks good except for one minor comment

2019-10-22 16:55 UTC, chilanti commented
> looks good except for one minor comment

Neeraj - not sure if it's me... but I don't see your minor comment...

2019-10-23 14:31 UTC, neeraj-laad commented on Dockerfile
> +ENV KUBE_LATEST_VERSION="v1.11.1"
Why do we call this LATEST if it is a fixed version?

2019-10-23 15:39 UTC, neeraj-laad approved these changes
LGTM

2019-10-23 15:39 UTC, merged